// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVrDTDAQT2xEchRuIdLroilAQgulVyArY',
    appId: '1:776452919172:web:46b8d78d9aa01e165bd7d1',
    messagingSenderId: '776452919172',
    projectId: 'kerigo-21a0b',
    authDomain: 'kerigo-21a0b.firebaseapp.com',
    storageBucket: 'kerigo-21a0b.firebasestorage.app',
    measurementId: 'G-SCB8SQJHZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR7sHzyUGMWjY4VUf9wTr39RSeD-Uc_uY',
    appId: '1:776452919172:android:caed52dafbea4ccc5bd7d1',
    messagingSenderId: '776452919172',
    projectId: 'kerigo-21a0b',
    storageBucket: 'kerigo-21a0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA_VOIvzPigkwALkVbx78uVNmuLTct9jo',
    appId: '1:776452919172:ios:e7eabd07e67f4e0b5bd7d1',
    messagingSenderId: '776452919172',
    projectId: 'kerigo-21a0b',
    storageBucket: 'kerigo-21a0b.firebasestorage.app',
    iosBundleId: 'com.ridy.taxi.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA_VOIvzPigkwALkVbx78uVNmuLTct9jo',
    appId: '1:776452919172:ios:46b258abfdfff1f55bd7d1',
    messagingSenderId: '776452919172',
    projectId: 'kerigo-21a0b',
    storageBucket: 'kerigo-21a0b.firebasestorage.app',
    iosBundleId: 'com.gotaxi.taxi.driverFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVrDTDAQT2xEchRuIdLroilAQgulVyArY',
    appId: '1:776452919172:web:46b8d78d9aa01e165bd7d1',
    messagingSenderId: '776452919172',
    projectId: 'kerigo-21a0b',
    authDomain: 'kerigo-21a0b.firebaseapp.com',
    storageBucket: 'kerigo-21a0b.firebasestorage.app',
    measurementId: 'G-SCB8SQJHZ9',
  );
}
